# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 12.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: tests
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: fastlane tests
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
